#!/usr/bin/env bash
# Configure and operate a 4-verifier + 4-trainer Ascend online MTP cluster.

set -euo pipefail

DEFAULT_CONFIG=/kos_ulan/spec_train/config/glm52-mtp3-4v4t.env
DEFAULT_REPO=/kos_ulan/spec_train/speculators
DEFAULT_CONTAINER_PREFIX=glm52-mtp3
DEFAULT_MTP_MODEL=/kos_ulan/models/GLM-5.2
DEFAULT_DATASET=/kos_ulan/datasets/glm52-mtp-online

usage() {
    cat <<'EOF'
Usage:
  manage_mtp_glm52_ascend_online_4v4t.sh configure \
    --verifier-ips IP0,IP1,IP2,IP3 \
    --trainer-ips IP0,IP1,IP2,IP3 \
    --container-prefix NAME [OPTIONS]

  manage_mtp_glm52_ascend_online_4v4t.sh COMMAND [--config FILE]

Commands:
  configure        Write the shared cluster configuration.
  preflight        Run non-training validation on all eight nodes.
  start-verifiers  Start four verifier containers in the background.
  wait-verifiers   Wait until all verifier health endpoints return HTTP 200.
  smoke            Start the two-step smoke job on four trainer nodes.
  train            Start the production online-cache training job.
  offline          Resume using only cached hidden states.
  status           Show matching containers and recent host-wrapper logs.
  stop             Stop this cluster's verifier/trainer containers.

Configure options:
  --verifier-ips CSV       Exactly four verifier host addresses.
  --trainer-ips CSV        Exactly four trainer host addresses.
  --container-prefix NAME  Prefix for all eight container names.
  --config FILE            Output path on the shared filesystem.
  --mtp-init-model PATH    BF16 GLM-5.2 model containing native MTP weights.
  --data-path PATH         Hugging Face training dataset.
  --repo-path PATH         Shared repository path visible on every host.
  --force                  Replace an existing config after making a backup.

Runtime environment overrides:
  SSH_USER=root SSH_PORT=22 SSH_IDENTITY_FILE=/path/to/key
  SSH_STRICT_HOST_KEY_CHECKING=accept-new HEALTH_TIMEOUT=7200
  MANAGER_DRY_RUN=1  # print remote SSH commands without executing them

The default paths allow subsequent commands to require only --config. The
script deliberately does not store passwords; configure SSH keys first.
EOF
}

fail() {
    printf 'ERROR: %s\n' "$*" >&2
    exit 2
}

quote() {
    printf '%q' "$1"
}

split_csv() {
    local value=$1
    local destination=$2
    local -a parsed=()
    IFS=',' read -r -a parsed <<<"$value"
    ((${#parsed[@]} == 4)) || fail "$destination requires exactly four values"
    local entry
    for entry in "${parsed[@]}"; do
        [[ -n $entry && $entry != *[[:space:]]* ]] || \
            fail "$destination contains an empty or whitespace value"
    done
    local -n output=$destination
    output=("${parsed[@]}")
}

write_config() {
    local verifier_csv= trainer_csv=
    local prefix=$DEFAULT_CONTAINER_PREFIX
    local config=$DEFAULT_CONFIG
    local mtp_model=$DEFAULT_MTP_MODEL
    local dataset=$DEFAULT_DATASET
    local repo=$DEFAULT_REPO
    local force=0
    while (( $# )); do
        case "$1" in
            --verifier-ips) verifier_csv=${2:-}; shift 2 ;;
            --trainer-ips) trainer_csv=${2:-}; shift 2 ;;
            --container-prefix) prefix=${2:-}; shift 2 ;;
            --config) config=${2:-}; shift 2 ;;
            --mtp-init-model) mtp_model=${2:-}; shift 2 ;;
            --data-path) dataset=${2:-}; shift 2 ;;
            --repo-path) repo=${2:-}; shift 2 ;;
            --force) force=1; shift ;;
            -h | --help) usage; exit 0 ;;
            *) fail "unknown configure option: $1" ;;
        esac
    done
    [[ -n $verifier_csv ]] || fail "--verifier-ips is required"
    [[ -n $trainer_csv ]] || fail "--trainer-ips is required"
    [[ $prefix =~ ^[A-Za-z0-9][A-Za-z0-9_.-]*$ ]] || \
        fail "invalid Docker container prefix: $prefix"
    local -a verifier_ips trainer_ips
    split_csv "$verifier_csv" verifier_ips
    split_csv "$trainer_csv" trainer_ips
    local -A seen=()
    local address
    for address in "${verifier_ips[@]}" "${trainer_ips[@]}"; do
        [[ -z ${seen[$address]:-} ]] || fail "duplicate node address: $address"
        seen[$address]=1
    done

    mkdir -p -- "$(dirname -- "$config")"
    if [[ -e $config ]]; then
        ((force == 1)) || \
            fail "config already exists; use --force to replace it: $config"
        cp -- "$config" "${config}.backup.$(date +%Y%m%d-%H%M%S)"
    fi
    local temporary
    temporary=$(mktemp "${config}.tmp.XXXXXXXX")
    {
        printf '# Generated by %s on %s\n' "${0##*/}" "$(date -Iseconds)"
        printf 'CLUSTER_VERIFIER_IPS=(\n'
        printf '  %q\n' "${verifier_ips[@]}"
        printf ')\nCLUSTER_TRAINER_IPS=(\n'
        printf '  %q\n' "${trainer_ips[@]}"
        printf ')\n'
        printf 'CONTAINER_NAME_PREFIX=%q\n' "$prefix"
        printf 'REMOTE_REPO_PATH=%q\n' "$repo"
        printf 'NIC_NAME=${NIC_NAME:-auto}\n'
        printf 'IMAGE=${IMAGE:-%q}\n' \
            'quay.io/ascend/vllm-ascend:v0.23.0rc1-a3'
        printf 'SHARED_ROOT=${SHARED_ROOT:-%q}\n' /kos_ulan
        printf 'VERIFIER_MODEL_PATH=${VERIFIER_MODEL_PATH:-%q}\n' \
            /mnt/xds/sfs/l00936201/glm52-w4a8-mg13/v1-ascend-modelslim-v4
        printf 'VERIFIER_SOURCE_MODEL_PATH=${VERIFIER_SOURCE_MODEL_PATH:-%q}\n' \
            /mnt/xds/sfs/GLM-5.2-W4A8-MG13/v1
        printf 'VERIFIER_QUANTIZATION_MODE=${VERIFIER_QUANTIZATION_MODE:-ascend}\n'
        printf 'MTP_INIT_MODEL_PATH=${MTP_INIT_MODEL_PATH:-%q}\n' "$mtp_model"
        printf 'DATA_PATH=${DATA_PATH:-%q}\n' "$dataset"
        printf 'TRAINER_MODE=${TRAINER_MODE:-smoke}\n'
        printf 'TRAINER_DATA_MODE=${TRAINER_DATA_MODE:-online-cache}\n'
        printf 'SMOKE_RUN_ID=${SMOKE_RUN_ID:-%q}\n' \
            "smoke-$(date +%Y%m%d-%H%M%S)"
        printf 'VERIFIER_MAX_MODEL_LEN=${VERIFIER_MAX_MODEL_LEN:-32769}\n'
        printf 'VERIFIER_MAX_NUM_SEQS=${VERIFIER_MAX_NUM_SEQS:-8}\n'
        printf 'VERIFIER_MAX_BATCHED_TOKENS=${VERIFIER_MAX_BATCHED_TOKENS:-32768}\n'
        printf 'TOTAL_SEQ_LEN=${TOTAL_SEQ_LEN:-32768}\n'
        printf 'REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-900}\n'
        printf 'MAX_RETRIES=${MAX_RETRIES:-3}\n'
        printf 'EPOCHS=${EPOCHS:-5}\n'
    } >"$temporary"
    chmod 600 "$temporary"
    mv -- "$temporary" "$config"
    printf 'CONFIG_STATUS=created\nCONFIG_FILE=%s\n' "$config"
    printf 'CONTAINER_PREFIX=%s\n' "$prefix"
}

CONFIG_FILE=$DEFAULT_CONFIG
parse_config_option() {
    while (( $# )); do
        case "$1" in
            --config) CONFIG_FILE=${2:-}; shift 2 ;;
            -h | --help) usage; exit 0 ;;
            *) fail "unknown option: $1" ;;
        esac
    done
}

load_config() {
    [[ -f $CONFIG_FILE ]] || fail "configuration not found: $CONFIG_FILE"
    # shellcheck disable=SC1090
    source "$CONFIG_FILE"
    declare -p CLUSTER_VERIFIER_IPS >/dev/null 2>&1 || \
        fail "CLUSTER_VERIFIER_IPS is missing"
    declare -p CLUSTER_TRAINER_IPS >/dev/null 2>&1 || \
        fail "CLUSTER_TRAINER_IPS is missing"
    ((${#CLUSTER_VERIFIER_IPS[@]} == 4)) || fail "expected four verifier IPs"
    ((${#CLUSTER_TRAINER_IPS[@]} == 4)) || fail "expected four trainer IPs"
    CONTAINER_NAME_PREFIX=${CONTAINER_NAME_PREFIX:-$DEFAULT_CONTAINER_PREFIX}
    REMOTE_REPO_PATH=${REMOTE_REPO_PATH:-$DEFAULT_REPO}
    SHARED_ROOT=${SHARED_ROOT:-/kos_ulan}
    ORCHESTRATOR_LOG_ROOT=${ORCHESTRATOR_LOG_ROOT:-$SHARED_ROOT/spec_train/logs/orchestrator}
}

ssh_args() {
    SSH_ARGS=(
        -p "${SSH_PORT:-22}"
        -o BatchMode=yes
        -o ConnectTimeout=10
        -o "StrictHostKeyChecking=${SSH_STRICT_HOST_KEY_CHECKING:-accept-new}"
    )
    if [[ -n ${SSH_IDENTITY_FILE:-} ]]; then
        SSH_ARGS+=(-i "$SSH_IDENTITY_FILE")
    fi
}

remote() {
    local host=$1
    shift
    ssh_args
    if [[ ${MANAGER_DRY_RUN:-0} == 1 ]]; then
        printf '[ssh]'
        printf ' %q' ssh "${SSH_ARGS[@]}" "${SSH_USER:-root}@${host}" "$@"
        printf '\n'
        return
    fi
    ssh "${SSH_ARGS[@]}" "${SSH_USER:-root}@${host}" "$@"
}

build_remote_command() {
    local destination=$1
    shift
    printf -v "$destination" '%q ' "$@"
}

start_node() {
    local host=$1 role=$2 index=$3 mode=${4:-}
    local container="$CONTAINER_NAME_PREFIX-$role$index"
    local verifier_host=${CLUSTER_VERIFIER_IPS[$index]:-}
    local host_log="$ORCHESTRATOR_LOG_ROOT/$container.host.log"
    local -a command=(
        env
        "NODE_IP=$host"
        "LOCAL_IP=$host"
        NIC_NAME=auto
        "ROLE=$role"
        "CONTAINER_NAME=$container"
    )
    case "$role" in
        verifier) command+=("VERIFIER_ID=$index") ;;
        smoke | trainer)
            command+=(
                "NODE_RANK=$index"
                NNODES=4
                "MASTER_ADDR=${CLUSTER_TRAINER_IPS[0]}"
                "VERIFIER_HOST=$verifier_host"
            )
            [[ -n $mode ]] && command+=("TRAINER_DATA_MODE=$mode")
            ;;
        preflight) ;;
        *) fail "unsupported role: $role" ;;
    esac
    command+=(
        bash "$REMOTE_REPO_PATH/examples/train/run_mtp_glm52_ascend_online_container.sh"
        "$CONFIG_FILE"
    )
    local serialized
    build_remote_command serialized "${command[@]}"
    local shell_command
    shell_command="mkdir -p $(quote "$ORCHESTRATOR_LOG_ROOT"); "
    shell_command+="cd $(quote "$REMOTE_REPO_PATH"); "
    shell_command+="nohup $serialized >$(quote "$host_log") 2>&1 </dev/null "
    shell_command+="& echo STARTED_PID=\$!"
    printf '[start] host=%s container=%s log=%s\n' "$host" "$container" "$host_log"
    remote "$host" "$shell_command"
}

run_preflight_node() {
    local host=$1 index=$2
    local container="$CONTAINER_NAME_PREFIX-preflight$index"
    local -a command=(
        env "NODE_IP=$host" "LOCAL_IP=$host" NIC_NAME=auto ROLE=preflight
        "CONTAINER_NAME=$container"
        bash "$REMOTE_REPO_PATH/examples/train/run_mtp_glm52_ascend_online_container.sh"
        "$CONFIG_FILE"
    )
    local serialized
    build_remote_command serialized "${command[@]}"
    printf '[preflight] host=%s\n' "$host"
    remote "$host" "cd $(quote "$REMOTE_REPO_PATH"); $serialized"
}

start_group() {
    local role=$1 mode=${2:-}
    local -n addresses=$3
    local index
    for index in "${!addresses[@]}"; do
        start_node "${addresses[$index]}" "$role" "$index" "$mode"
    done
}

wait_verifiers() {
    local timeout=${HEALTH_TIMEOUT:-7200}
    local started=$SECONDS
    local -a ready=(0 0 0 0)
    while :; do
        local index remaining=0 code
        for index in "${!CLUSTER_VERIFIER_IPS[@]}"; do
            if [[ ${ready[$index]} == 1 ]]; then
                continue
            fi
            code=$(curl -sS -m 3 -o /dev/null -w '%{http_code}' \
                "http://${CLUSTER_VERIFIER_IPS[$index]}:${VERIFIER_PORT:-8077}/health" \
                2>/dev/null || true)
            if [[ $code == 200 ]]; then
                ready[$index]=1
                printf '[healthy] verifier%d=%s\n' \
                    "$index" "${CLUSTER_VERIFIER_IPS[$index]}"
            else
                remaining=$((remaining + 1))
            fi
        done
        ((remaining > 0)) || return 0
        ((SECONDS - started < timeout)) || \
            fail "timed out waiting for $remaining verifier(s)"
        sleep 15
    done
}

show_role_status() {
    local role=$1
    local -n addresses=$2
    local index host container
    for index in "${!addresses[@]}"; do
        host=${addresses[$index]}
        container="$CONTAINER_NAME_PREFIX-$role$index"
        printf '\n[status] host=%s container=%s\n' "$host" "$container"
        local status_command
        status_command="docker ps -a --filter name=^/$(quote "$container")\$ "
        status_command+="--format '{{.Names}} {{.Status}}'; "
        status_command+="tail -n 8 "
        status_command+="$(quote "$ORCHESTRATOR_LOG_ROOT/$container.host.log") "
        status_command+="2>/dev/null || true"
        remote "$host" "$status_command" || true
    done
}

show_status() {
    show_role_status verifier CLUSTER_VERIFIER_IPS
    show_role_status trainer CLUSTER_TRAINER_IPS
    show_role_status smoke CLUSTER_TRAINER_IPS
}

stop_role() {
    local role=$1
    local -n addresses=$2
    local index host container
    for index in "${!addresses[@]}"; do
        host=${addresses[$index]}
        container="$CONTAINER_NAME_PREFIX-$role$index"
        printf '[stop] host=%s container=%s\n' "$host" "$container"
        remote "$host" \
            "docker stop -t 30 $(quote "$container") >/dev/null 2>&1 || true" || true
    done
}

stop_cluster() {
    stop_role verifier CLUSTER_VERIFIER_IPS
    stop_role trainer CLUSTER_TRAINER_IPS
    stop_role smoke CLUSTER_TRAINER_IPS
}

COMMAND=${1:-}
[[ -n $COMMAND ]] || { usage; exit 2; }
shift

if [[ $COMMAND == configure ]]; then
    write_config "$@"
    exit
fi

parse_config_option "$@"
load_config

case "$COMMAND" in
    preflight)
        index=0
        for host in "${CLUSTER_VERIFIER_IPS[@]}" "${CLUSTER_TRAINER_IPS[@]}"; do
            run_preflight_node "$host" "$index"
            index=$((index + 1))
        done
        ;;
    start-verifiers) start_group verifier '' CLUSTER_VERIFIER_IPS ;;
    wait-verifiers) wait_verifiers ;;
    smoke) start_group smoke online-cache CLUSTER_TRAINER_IPS ;;
    train) start_group trainer online-cache CLUSTER_TRAINER_IPS ;;
    offline) start_group trainer offline CLUSTER_TRAINER_IPS ;;
    status) show_status ;;
    stop) stop_cluster ;;
    -h | --help | help) usage ;;
    *) fail "unknown command: $COMMAND" ;;
esac
