#!/usr/bin/env python3
"""Derive an isolated online-smoke YAML from a filled Ascend production YAML."""

from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path

from render_ascend_mtp_cluster_yaml import load_flat_yaml, validate


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--smoke-seq-len", type=int, default=1024)
    parser.add_argument("--smoke-samples", type=int, default=256)
    return parser.parse_args()


def _scalar(config: dict[str, str | list[str]], key: str) -> str:
    value = config.get(key)
    if not isinstance(value, str) or not value:
        raise ValueError(f"source configuration is missing {key}")
    return value


def derive_config(
    source: Path,
    *,
    run_id: str,
    smoke_seq_len: int,
    smoke_samples: int,
) -> dict[str, str | list[str]]:
    config = load_flat_yaml(source)
    validate(config)
    trainers = config.get("trainer_ips")
    if not isinstance(trainers, list) or len(trainers) not in {2, 4, 6}:
        raise ValueError("online smoke requires exactly two, four, or six trainers")
    if re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_.-]*", run_id) is None:
        raise ValueError("run-id must contain only Docker/path-safe characters")
    if smoke_seq_len <= 0 or smoke_seq_len > int(_scalar(config, "total_seq_len")):
        raise ValueError("smoke-seq-len must be in [1, total_seq_len]")
    if smoke_samples <= 0:
        raise ValueError("smoke-samples must be positive")

    shared_root = _scalar(config, "shared_root").rstrip("/")
    temporary_hidden_states = (
        f"{shared_root}/spec_train/hidden_states/quick-online-smoke-{run_id}"
    )
    config.update(
        {
            "cluster_name": f"glm52-quick-online-smoke-{run_id}",
            # Online transfer returns a file handle to another host, so both
            # paths must be the same shared, isolated directory. Smoke mode
            # consumes each handle and immediately deletes it.
            "hidden_states_path": temporary_hidden_states,
            "verifier_staging_path": temporary_hidden_states,
            "output_path": f"{shared_root}/spec_train/ckpts/glm52-quick-online",
            "log_root": f"{shared_root}/spec_train/logs/glm52-quick-online",
            "smoke_seq_len": str(smoke_seq_len),
            "smoke_samples": str(smoke_samples),
            "num_workers": "1",
            "prefetch_factor": "1",
            "verifier_max_num_seqs": "2",
            "verifier_gpu_memory_utilization": "0.62",
            "fsdp_experts_per_unit": "2",
            "mtp_logits_chunk_size": "128",
            "mtp_activation_checkpointing": "false",
            "mtp_training_strategy": "sampled_step",
            "memory_log_freq": "1",
            "trainer_mode": "smoke",
            "trainer_data_mode": "online-cache",
            "smoke_run_id": run_id,
        }
    )
    validate(config)
    return config


def write_flat_yaml(config: dict[str, str | list[str]], output: Path) -> None:
    lines = [
        "# Generated by make_ascend_mtp_online_smoke_config.py; do not edit.",
        "# Request-scoped hidden states are read and deleted by the smoke trainer.",
    ]
    for key, value in config.items():
        if isinstance(value, list):
            lines.append(f"{key}:")
            lines.extend(f"  - {json.dumps(item)}" for item in value)
        else:
            lines.append(f"{key}: {json.dumps(value)}")
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_name(f".{output.name}.tmp.{os.getpid()}")
    temporary.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.replace(temporary, output)


def main() -> None:
    args = parse_args()
    config = derive_config(
        args.source,
        run_id=args.run_id,
        smoke_seq_len=args.smoke_seq_len,
        smoke_samples=args.smoke_samples,
    )
    write_flat_yaml(config, args.output)
    print(f"SMOKE_CONFIG={args.output}")
    print(f"SMOKE_RUN_ID={args.run_id}")
    print(f"SMOKE_SEQ_LEN={args.smoke_seq_len}")


if __name__ == "__main__":
    main()
